// <auto-generated />
using System;
using HeroesApp.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HeroesApp.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.8");

            modelBuilder.Entity("HeroesApp.Domain.Entities.Hero", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<float>("Altura")
                        .HasColumnType("REAL");

                    b.Property<DateTime?>("DataNascimento")
                        .HasColumnType("TEXT");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("NomeHeroi")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<float>("Peso")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.ToTable("Herois", (string)null);
                });

            modelBuilder.Entity("HeroesApp.Domain.Entities.Herosuperpower", b =>
                {
                    b.Property<int>("HeroiId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SuperpoderId")
                        .HasColumnType("INTEGER");

                    b.HasKey("HeroiId", "SuperpoderId");

                    b.HasIndex("SuperpoderId");

                    b.ToTable("HeroisSuperpoderes", (string)null);
                });

            modelBuilder.Entity("HeroesApp.Domain.Entities.Superpower", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Descricao")
                        .HasColumnType("TEXT");

                    b.Property<string>("SuperpoderNome")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("Superpoder");

                    b.HasKey("Id");

                    b.ToTable("Superpoderes", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Descricao = "Força sobre-humana",
                            SuperpoderNome = "Força"
                        },
                        new
                        {
                            Id = 2,
                            Descricao = "Capacidade de voar",
                            SuperpoderNome = "Voo"
                        },
                        new
                        {
                            Id = 3,
                            Descricao = "Ficar invisível aos olhos",
                            SuperpoderNome = "Invisibilidade"
                        });
                });

            modelBuilder.Entity("HeroesApp.Domain.Entities.Herosuperpower", b =>
                {
                    b.HasOne("HeroesApp.Domain.Entities.Hero", "Heroi")
                        .WithMany("HeroisSuperpoderes")
                        .HasForeignKey("HeroiId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HeroesApp.Domain.Entities.Superpower", "Superpoder")
                        .WithMany("HeroisSuperpoderes")
                        .HasForeignKey("SuperpoderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Heroi");

                    b.Navigation("Superpoder");
                });

            modelBuilder.Entity("HeroesApp.Domain.Entities.Hero", b =>
                {
                    b.Navigation("HeroisSuperpoderes");
                });

            modelBuilder.Entity("HeroesApp.Domain.Entities.Superpower", b =>
                {
                    b.Navigation("HeroisSuperpoderes");
                });
#pragma warning restore 612, 618
        }
    }
}
